Controllers/CartController.cs
using Sports;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sports.Controllers;

namespace Sports.Models
{

    public class CartController : Controller
    {
        private Sports_Zone_DbEntities db = new Sports_Zone_DbEntities();
        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }
        private int isExisting(string id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.ProId == id)
                {
                    return i;
                }
            }
            return -1;
        }
        public ActionResult Delete(string id)
        {
            int index = isExisting(id);
            List<Item> cart = (List<Item>)Session["cart"];
            cart.RemoveAt(index);
            Session["cart"] = cart;
            return View("cart");
        }
        public ActionResult OrderNow(string id)
        {
            if (Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item(db.Products.Find(id), 1));
                Session["cart"] = cart;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                int index = isExisting(id);
                if (index == -1)
                {
                    cart.Add(new Item(db.Products.Find(id), 1));
                }
                else
                {
                    cart[index].quantity++;
                }
                Session["cart"] = cart;
            }
            return View("cart");


        }
    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sports;

namespace Sports.Controllers
{
    public class ProductsController : Controller
    {
        private Sports_Zone_DbEntities db = new Sports_Zone_DbEntities();

        // GET: Products
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProId,ProName,ProDescription,ProPrice,Stock,ProPic")] Product product, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                string filename = Path.GetFileName(file.FileName);
                string upath = Path.Combine(Server.MapPath("~/Images"), filename);
                file.SaveAs(upath);
                product.ProPic = filename;
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProId,ProName,ProDescription,ProPrice,Stock,ProPic")] Product product, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Products/Create.cshtml
@model Sports.Product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProPic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" , id="file" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Products/Delete.cshtml
@model Sports.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProPic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProPic)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Products/Details.cshtml
@model Sports.Product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProPic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProPic)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Products/Edit.cshtml
@model Sports.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit","Products",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProId)

        <div class="form-group">
            @Html.LabelFor(model => model.ProName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>

         <div class="form-group">
            @Html.LabelFor(model => model.ProPic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*<img src="@Url.Content(Model.ProPic)" height="70" width="100" />*@
                <input type="file" name="file" , id="file" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Products/Index.cshtml
@model IEnumerable<Sports.Product>

    @{
        ViewBag.Title = "Index";
    }

    <h2>Products</h2>

  
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProName)
            </th>
            <th>
                Product Pic
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stock)
            </th>

            <th>Buy</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProName)
                </td>

                <td>
                    <img src="@Url.Content("~/Images/"+item.ProPic)"
                         style="height:200px;width:200px" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stock)
                </td>
                <td>
                   
                    @Html.ActionLink("Add To Cart", "OrderNow", "Cart", new { id = item.ProId }, null)
                </td>

              
            </tr>
        }

    </table>